#!/bin/bash
# Simple dashboard generator using Thalo CLI
# Usage: ./dashboard-cli.sh

NOTES_DIR="${NOTES_DIR:-$HOME/Documents/Notes}"
OUTPUT="${NOTES_DIR}/dashboard.md"

cd "$NOTES_DIR" || exit 1

echo "Generating dashboard..."

# Get counts using thalo query
ACTIVE_PROJECTS=$(thalo query 'project where status = "active"' 2>/dev/null | grep -c "^project")
PAUSED_PROJECTS=$(thalo query 'project where status = "paused"' 2>/dev/null | grep -c "^project")
COMPLETED_PROJECTS=$(thalo query 'project where status = "completed"' 2>/dev/null | grep -c "^project")

TOTAL_REFS=$(thalo query 'reference' 2>/dev/null | grep -c "^reference")
UNREAD_REFS=$(thalo query 'reference where status = "unread"' 2>/dev/null | grep -c "^reference")
READ_REFS=$(thalo query 'reference where status = "read"' 2>/dev/null | grep -c "^reference")

TOTAL_LORE=$(thalo query 'lore' 2>/dev/null | grep -c "^lore")

# Generate markdown
cat > "$OUTPUT" << EOF
# 📊 Project Dashboard

> Auto-generated: $(date '+%Y-%m-%d %H:%M')

## Quick Stats

| Metric | Count |
|--------|-------|
| Active Projects | $ACTIVE_PROJECTS |
| Paused Projects | $PAUSED_PROJECTS |
| Total References | $TOTAL_REFS |
| Unread Papers | $UNREAD_REFS |
| Lore Entries | $TOTAL_LORE |

## 🟢 Active Projects

$(thalo query 'project where status = "active"' 2>/dev/null | while read -r line; do
  title=$(echo "$line" | sed 's/.*"\([^"]*\)".*/\1/')
  linkid=$(echo "$line" | grep -o '\^[a-z0-9-]*' | head -1)
  echo "- [[$linkid]] $title"
done)

## ⏸️ Paused Projects

$(thalo query 'project where status = "paused"' 2>/dev/null | while read -r line; do
  title=$(echo "$line" | sed 's/.*"\([^"]*\)".*/\1/')
  linkid=$(echo "$line" | grep -o '\^[a-z0-9-]*' | head -1)
  echo "- [[$linkid]] $title"
done)

## 📚 References

| Status | Count |
|--------|-------|
| Unread | $UNREAD_REFS |
| Read | $READ_REFS |
| **Total** | **$TOTAL_REFS** |

---
*Generated by dashboard-cli.sh*
EOF

echo "Dashboard written to: $OUTPUT"
